// Copyright 2020 The simdutf authors
// Copyright (C) 2026 Kumo inc. and its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// /include/vamos/vamos_version.h automatically generated by release.py,
// do not change by hand
#ifndef VAMOS_VAMOS_VERSION_H
#define VAMOS_VAMOS_VERSION_H

/** The version of vamos being used (major.minor.revision) */
#define VAMOS_VERSION "6.2.0"

namespace vamos {
enum {
  /**
   * The major version (MAJOR.minor.revision) of vamos being used.
   */
  VAMOS_VERSION_MAJOR = 1,
  /**
   * The minor version (major.MINOR.revision) of vamos being used.
   */
  VAMOS_VERSION_MINOR = 2,
  /**
   * The revision (major.minor.REVISION) of vamos being used.
   */
  VAMOS_VERSION_REVISION = 0
};
} // namespace vamos

#endif // VAMOS_VAMOS_VERSION_H
