// Copyright (C) 2024 Kumo inc.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// /include/vamos/vamos_version.h automatically generated by release.py,
// do not change by hand
#ifndef VAMOS_VAMOS_VERSION_H
#define VAMOS_VAMOS_VERSION_H

/** The version of vamos being used (major.minor.revision) */
#define VAMOS_VERSION "6.2.0"

namespace vamos {
enum {
  /**
   * The major version (MAJOR.minor.revision) of vamos being used.
   */
  VAMOS_VERSION_MAJOR = 1,
  /**
   * The minor version (major.MINOR.revision) of vamos being used.
   */
  VAMOS_VERSION_MINOR = 2,
  /**
   * The revision (major.minor.REVISION) of vamos being used.
   */
  VAMOS_VERSION_REVISION = 0
};
} // namespace vamos

#endif // VAMOS_VAMOS_VERSION_H
